### ISSUE TITLE
Prebuilt binary didn't work on armv6

### ISSUE THREAD

**Issue by steals** [rhasspy/webrtc-noise-gain#12]
After upgrade Home Assistant to 2023.10.3 it stopped working due to the `Illegal Instruction` error. Further investigation identified that `webrtc-noise-gain` libe throwing that error. See https://github.com/MichaIng/DietPi/issues/6683 and https://github.com/home-assistant/core/issues/102220
But the recompilaiton on the local machine solves the issue.  So it looks like something is configured incorrectly on the built host.

**Comment by synesthesiam** [comment]
I've uploaded `armv6` wheels to PyPI. I'm not sure if `pip` will select them correctly, though.

**Comment by paulwitt** [comment]
Yea, it doesn't work.  Manually installed the .whl and tried this:

```
>>> from webrtc_noise_gain import AudioProcessor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/homeassistant-satellite/.venv/lib/python3.11/site-packages/webrtc_noise_gain/__init__.py", line 1, in <module>
    from webrtc_noise_gain_cpp import AudioProcessor
ModuleNotFoundError: No module named 'webrtc_noise_gain_cpp'

```

**Comment by synesthesiam** [comment]
I don't have the resources to support 32-bit ARM
