### ISSUE TITLE
RISC-V support: What's needed?

### ISSUE THREAD

**Issue by IngwiePhoenix** [rhasspy/webrtc-noise-gain#18]
Hello there!

So, first off:

```
(homeassistant) root@riscboi /n/s/homeassistant [0|1]# pip install -U webrtc-noise-gain
Collecting webrtc-noise-gain
  Using cached webrtc_noise_gain-1.2.3.tar.gz (3.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/nvme/srv/homeassistant/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/nvme/srv/homeassistant/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/nvme/srv/homeassistant/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2scqyq2w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2scqyq2w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2scqyq2w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-2scqyq2w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 482, in <module>
      ValueError: Unsupported machine: riscv64
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I looked at the `setup.py` for a while and took note of which `-D`efines and `.c/.cc` sources are added to the build. Well, is there a way to help to make RISC-V work?

I run a relatively "standard" Debian Unstable (Trixie) so all the default tools are here (gcc, alsa, ffmpeg, ...). Since this seems to be the last package holding back Home Assistant's `assist_pipeline`, I would love to get this sorted. :)

Kind regards,
Ingwie

**Comment by gdt** [comment]
You're going to have to do two things.  One is to add a block to setup.py to switch on risc-v.  If it's BE, then you have even more work to do as there seems to be a "all the world is LE" define -- which is obviously not true, but perhaps webrtc-noise-gain has that assumption.

The other thing, which might be hard and might not be, is to make webrtc-noise-gain work on risc-v.   I am unclear on status, but have a vague memory that it's not really maintained upstream and is thus vendored here.  But don't trust me on that; figure it out :-)

(I'm simply a user here, reading setup.py because this was not portable to BSDs, and hoping to run NetBSD on risc-v some year.)

**Comment by martinwozenilek** [comment]
At least for Gentoo it seems we have now a solution. Andrew created a patch for risc64 for the ebuild: 

http://forum.rvspace.org/t/webrtc-noise-gain-for-risc-v/4443/2?u=martin.wozenilek

I've tested this with the VisionFive2-Gentoo-HomeAssistant system and it looks okay.

**Comment by apcameron** [comment]
Here is the patch that you can try
<pre>diff &apos;--color=auto&apos; -Naur a/setup.py b/setup.py
--- a/setup.py	2024-07-10 20:25:14.667065285 +0100
+++ b/setup.py	2024-07-10 20:24:41.386342397 +0100
@@ -478,6 +478,12 @@
         &quot;-DWEBRTC_ARCH_32_BITS&quot;,
         &quot;-DPFFFT_SIMD_DISABLE&quot;,
     ]
+elif machine in (&quot;riscv64&quot;, &quot;risc&quot;):
+    # Riscv)
+    machine_cflags += [
+        &quot;-DWEBRTC_ARCH_RISCV&quot;,
+        &quot;-DWEBRTC_ARCH_64_BITS&quot;,
+    ]
 else:
     raise ValueError(f&quot;Unsupported machine: {machine}&quot;)
</pre>

**Comment by eshattow** [comment]
Hi @gdt   (cc attn: @synesthesiam )

> You're going to have to do two things. One is to add a block to setup.py to switch on risc-v. If it's BE, then you have even more work to do as there seems to be a "all the world is LE" define -- which is obviously not true, but perhaps webrtc-noise-gain has that assumption.

Simply done. No drama there.

> 
> The other thing, which might be hard and might not be, is to make webrtc-noise-gain work on risc-v. I am unclear on status, but have a vague memory that it's not really maintained upstream and is thus vendored here. But don't trust me on that; figure it out :-)

I am confused by this. Is there another webrtc-noise-gain ?

> 
> (I'm simply a user here, reading setup.py because this was not portable to BSDs, and hoping to run NetBSD on risc-v some year.)

PR rhasspy/webrtc-noise-gain/pull/27 is ready for review, if you can spare a moment please?

**Comment by gdt** [comment]
> I am confused by this. Is there another webrtc-noise-gain ?

I am now confused too.   webrtc-noise-gain describes itself as "Tiny wrapper around webrtc-audio-processing for noise suppression/auto gain only" but seems to have code, not just wrapper.   If it were a wrapper, you'd be first making webrtc-audio-processing work for RISC-V and then a PR here to use that version.   In the HA world, often HA people take on maintenance of needed things when upstream isn't maintaining any more.

I went looking and found a bunch of things.  Most of them are not what you might be looking for, but it's an example of how confusing this is.
  - https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing/
  - https://www.freedesktop.org/software/pulseaudio/webrtc-audio-processing/
  - https://github.com/cross-platform/webrtc-audio-processing
  - https://github.com/taktod/pulseaudio-webrtc-audio-processing
  - https://github.com/get-wrecked/webrtc-audioprocessing
  -
